### ISSUE TITLE
can't insert ChunkThread bundle for non-existent entity

### ISSUE THREAD

**Issue by bbarker** [splashdust/bevy_voxel_world#12]
I just received this panic for the first time. I don't know if it is a rare error or elated to some texture work I added. I will report back later. But it doesn't seem to be texture related.

```

thread 'main' panicked at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:1022:13:
error[B0003]: Could not insert a bundle (of type `bevy_voxel_world::chunk::ChunkThread`) for entity 7619v4 because it doesn't exist in this World.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic when applying buffers for system `bevy_voxel_world::voxel_world_internal::remesh_dirty_chunks`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

Can potentially reproduce using https://github.com/bbarker/speed-farmer/commit/7525baa9827a5d36bf793a78f67abe3cb7ff6628 (`cargo run` and play around for a while).

**Comment by bbarker** [comment]
I have this seen this recur;

Current count: 2

**Comment by bbarker** [comment]
backtrace:
```

thread 'main' panicked at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:1022:13:
error[B0003]: Could not insert a bundle (of type `bevy_voxel_world::chunk::ChunkThread`) for entity 5449v3 because it doesn't exist in this World.
stack backtrace:                                                                                                                                                                              
   0: rust_begin_unwind                                                                                                                                                                       
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5                                               
   1: core::panicking::panic_fmt                                                                                                                                                              
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: <bevy_ecs::system::commands::Insert<T> as bevy_ecs::system::commands::Command>::apply                                                                                          [56/1966]
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:1022:13            
   3: bevy_ecs::system::commands::command_queue::CommandQueue::push::{{closure}}
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/command_queue.rs:65:36
   4: core::ops::function::FnOnce::call_once                                                                                                                                                  
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5     
   5: bevy_ecs::system::commands::command_queue::CommandQueue::apply_or_drop_queued
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/command_queue.rs:146:33
   6: bevy_ecs::system::commands::command_queue::CommandQueue::apply
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/command_queue.rs:108:9
   7: bevy_ecs::system::commands::<impl bevy_ecs::system::system_param::SystemBuffer for bevy_ecs::system::commands::command_queue::CommandQueue>::apply
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:123:14
   8: <bevy_ecs::system::system_param::Deferred<T> as bevy_ecs::system::system_param::SystemParam>::apply                         
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/system_param.rs:909:21             
   9: <(P0,P1) as bevy_ecs::system::system_param::SystemParam>::apply
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/system_param.rs:1378:19
  10: bevy_ecs::system::commands::_::<impl bevy_ecs::system::system_param::SystemParam for bevy_ecs::system::commands::Commands>::apply
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/commands/mod.rs:112:10
  11: bevy_ecs::schedule::executor::multi_threaded::apply_deferred::{{closure}}
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/multi_threaded.rs:691:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5                    
  13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9         
  14: std::panicking::try::do_call         
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40                   
  15: std::panicking::try                                                                      
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  16: std::panic::catch_unwind                                                                                                                                                                
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14 
  17: bevy_ecs::schedule::executor::multi_threaded::apply_deferred                                                                                                                            
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/multi_threaded.rs:690:19
  18: <bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run         
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/multi_threaded.rs:242:23
  19: bevy_ecs::world::World::try_run_schedule::{{closure}}                                                                                                                                   
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2074:55
  20: bevy_ecs::world::World::try_schedule_scope                                                                                                                                              
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2007:21
  21: bevy_ecs::world::World::try_run_schedule                                                                                                                                                
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2074:9
  22: bevy_app::main_schedule::Main::run_main::{{closure}}                                                                                                                                    
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/main_schedule.rs:152:31
  23: bevy_ecs::world::World::resource_scope                                                                                                                                                  
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:1571:22
  24: bevy_app::main_schedule::Main::run_main                                                                                                                                                 
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/main_schedule.rs:150:9
  25: core::ops::function::FnMut::call_mut                                                                                                                                                    
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:166:5
  26: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut                                                                                                   
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
  27: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run::call_inner
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/exclusive_function_system.rs:207:21
  28: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/exclusive_function_system.rs:210:17
  29: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/system/exclusive_function_system.rs:107:19
  30: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::{{closure}}
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/single_threaded.rs:92:21
  31: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  33: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  34: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  35: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  36: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/schedule/executor/single_threaded.rs:91:27
  37: bevy_ecs::world::World::run_schedule::{{closure}}
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2088:51
  38: bevy_ecs::world::World::try_schedule_scope
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2007:21
  39: bevy_ecs::world::World::schedule_scope
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2059:9
  40: bevy_ecs::world::World::run_schedule
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.1/src/world/mod.rs:2088:9
  41: bevy_app::app::App::update
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:266:24
  42: bevy_winit::winit_runner::{{closure}}
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:836:25
  43: winit::platform_impl::platform::sticky_exit_callback
  44: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:358:17
  45: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:483:27
  46: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:498:25
  47: winit::platform_impl::platform::EventLoop<T>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:792:56
  48: winit::event_loop::EventLoop<T>::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305:25
  49: bevy_winit::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:235:16
  50: bevy_winit::winit_runner
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:920:9
  51: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  52: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  53: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  54: bevy_app::app::App::run
             at /home/bbarker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:314:9
  55: speed_farmer::main
             at ./src/main.rs:51:5
  56: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic when applying buffers for system `bevy_voxel_world::voxel_world_internal::remesh_dirty_chunks`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
